defaults: &defaults
  alidayu:
    app_key: 123
    app_secret: xxx
    post_url: 'http://gw.api.taobao.com/router/rest'
    product: "vcooline"
    sms_templates:
      - name: "sign_up"
        sms_free_sign_name: "vcooline" # 短信签名
        sms_template_code: "SMS_6475458" # 短信模板

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
